spring:
  profiles: local
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/aramark?zeroDateTimeBehavior=convertToNull
    username: root
    password:
liquibase:
  change-log: classpath:db-changelog/changelog-master.xml

---